run_name: 07_11/d30_k_7_depth4
seed: 123


# data
train_size: 50000
test_size: 5000
dim: 30
spec: "{7}"
noise_std: 0.0
shuffle_labels: false


# model
width: 256
depth: 4
activation: relu


# training
epochs: 1000
lr: 2.0e-3
optimizer: gd
momentum: 0.0
mode: gd # gd or sgd
batch_size: 


# device
device: cuda


# kernel metrics
compute_kernel: true
compute_kernel_every: 5
kernel_set: train # train or test
max_kernel_points: 25000
last_top_k: 15
lower_top_k: 15
betas: [0.2, 0.2, 0.2]
track_U: true
save_transfers: true