run_name: 08_11/d30_k_7_depth3_2_shuffle
seed: 123


# data, spec={5}
train_size: 80000
test_size: 5000
dim: 50
spec: "{1,2,3,4,5}"
noise_std: 0.0
shuffle_labels: true


# model
width: 256
depth: 4
activation: relu


# training
epochs: 100
lr: 5.0e-3
optimizer: gd
momentum: 0.0
mode: gd # gd or sgd
batch_size: 


# device
device: cuda


# kernel metrics
compute_kernel: true
compute_kernel_every: 10
kernel_set: train # train or test
max_kernel_points: 50000
last_top_k: 15
lower_top_k: 15
betas: [0.2, 0.2, 0.2]
track_U: true
save_transfers: true