run_name: svhn3_L4_epoch200_try2
seed: 42

# data
data_dir: data/SVHN/raw
dataset: svhn
train_size: 73257
test_size: 26032
dim: 3072           # Adjust if necessary

# training
epochs: 120
lr: 0.001            # learning rate
model: MLP          # Or ResNet18
mode: sgd
optimizer: adam     # USE ADAM IF DOESN'T WORK
momentum: 0.0       # =0.0 no momentum applied, normal values are 0.9,0.99
batch_size: 128
weight_decay: 0.0   # keep no explicit weight decay unless you want it

# loss & metrics
loss: cross_entropy   # <-- change from mse to cross-entropy
report_accuracy: true # always compute & report accuracy (train & test)

# model
width: 1024  # GO TO 1024 IF DOESN'Y WORK
depth: 4    # GO TO 4 IF DOESN'T WORK
activation: relu
num_classes: 10

# device
device: cuda

# other
spec: ""              # Provide a default or meaningful value if required
noise_std: 0.0        # Standard deviation of noise (set to 0.0 if not needed)
shuffle_labels: false # Whether to shuffle labels (set to false if not needed)